### ISSUE TITLE
Broken link  on FOG05 Wiki page

### ISSUE THREAD

**Issue by bmullan** [eclipse/fog05#105]
On the FOG05 Wiki page the link;

> these interface defined [here](https://github.com/eclipse/fog05/tree/master/fog05/interfaces) are for

is broken.

just fyi

**Comment by gabrik** [comment]
Thanks @bmullan you are right, all the wiki is pretty outdated and need to be improved

**Comment by gabrik** [comment]
Updated wiki and fixed broken links
