### ISSUE TITLE
MAC address mapping is not working

### ISSUE THREAD

**Issue by milangroshev** [eclipse/fog05#113]
Deploying containers using LXD plugin with static MAC address is not working. The key "mac_address" from the descriptor is not taken into account when creating the containers.

By defining the "mac_address" in the descriptor i would have expected that specific interface of the deployed container would get the pre-defined MAC address.

Example of descriptor containing the  mac_address key:

    "uuid": "3b4251a7-468f-4d64-b78c-8e2dfd9451e3",
    "name": "hostapd0",
    "computation_requirements": {
        "cpu_arch": "x86_64",
        "cpu_min_freq": 0.0,
        "cpu_min_count": 1,
        "ram_size_mb": 128.0,
        "storage_size_gb": 5.0
    },
    "image": {
        "uri": "file:///home/netcom/repository/hostapd.tar.gz",
        "checksum": "26eda4b4bae4dad871ec9fab9c51af3d3517e8db5256af1d1bbc743a4ff4d8ac",
        "format": "tar.gz"
    },
    "hypervisor": "LXD",
    "migration_kind": "LIVE",
    "depends_on": [],
    "interfaces": [
        {
            "name": "mgmt",
            "is_mgmt": false,
            "if_type": "INTERNAL",
            "mac_address": "be:ef:be:ef:00:02",
            "virtual_interface": {
                "intf_type": "VIRTIO",
                "vpci": "0:0:0",
                "bandwidth": 10
            },
            "cp_id": "2192bb19-a3f7-4b59-9473-eeec9573fb3b"
        },
        {
            "name": "wlan0",
            "is_mgmt": false,
            "if_type": "EXTERNAL",
            "mac_address": "be:ef:be:ef:b0:01",
            "virtual_interface": {
                "intf_type": "PHYSICAL",
                "vpci": "wlan0",
                "bandwidth": 10
            },
            "cp_id": ""
        }
    ],
    "io_ports": [],
    "connection_points": [
        {
            "uuid": "2192bb19-a3f7-4b59-9473-eeec9573fb3b",
            "pair_id": "6cc2aa30-1dcf-4c93-a57e-433fd0bd498e"
        }
    ]
}

 - OS: Ubuntu
 - Version 16.04
 - Involved plugin LXD
- LXD version: 3.14
- pylxd: 2.2.10

**Comment by gabrik** [comment]
Thanks @milangroshev for this report, you are right, even if the code for taking that in account is in place it is not working.

I'm working on this, should be part of my next PR.

**Comment by gabrik** [comment]
#114 should have solved this
waiting user confirmation
