### ISSUE TITLE
[BUG] 2nd FDU interface not receiving an IP address

### ISSUE THREAD

**Issue by Davide-DD** [eclipse/fog05#120]
**Describe the bug**
I have a LXC container with 2 network interfaces, both INTERNAL and VIRTIO, each one connected to a different ELAN. While the 1st interface is obtaining an IP address, the 2nd one is not receiving any IP address.

**To Reproduce**

1. Add 1st and 2nd network
2. Instance the FDU

Here are the files I'm using:
[Archivio.zip](https://github.com/eclipse/fog05/files/3343059/Archivio.zip)

**Expected behavior**
I expected to get an IP address for both interfaces, but I'm probably stating something wrong in the configuration file, I think.

**Desktop:**
 - OS: Linux Ubuntu
 - Version: 18.04.2
 - Involved plugin: LXD (LXC 3.14, pylxd: 2.2.10), LinuxBridge

**Comment by gabrik** [comment]
Hi @Davide-DD, this is not a bug, your image is not just asking (ie. using DHCP) for an address in the second inteface.

Just tested using as image with the dhcp configured in both eth0 and eth0 and it was working.

As an hint, for LXD containers the name of the interface specified in the descriptor is also the name that will be used inside the container, to in your case you need a container that will use dhcp on interfaces eth0 and eth1 

eg with an /etc/network/interfaces like this

```
auto eth0
iface eth0 inet dhcp

auto eth1
iface inet dhcp
```

Also the vpci is parameter is not used at the moment so you can leave it as 0:0:0

Let me know if this solves the issue

**Comment by Davide-DD** [comment]
Thank you very much, it was exactly what you were suggesting.
