### ISSUE TITLE
[BUG] Can't get Linux plugin to connect to the node

### ISSUE THREAD

**Issue by Davide-DD** [eclipse/fog05#122]
**Describe the bug**
When I try to run Linux plugin, it throws an exception and exit.

**To Reproduce**
1. Launch YAKS
2. Launch fagent
3. Launch Linux plugin
[Linux_log.txt](https://github.com/eclipse/fog05/files/3369850/Linux_log.txt)

**Expected behavior**
I expected to connect the plugin to the node.

**Desktop**
 - OS: Linux Ubuntu
 - Version: 16.04
 - Involved plugin: Linux

**Additional context**
This bug happened after I pulled the last changes of the repo and reinstalled everything (commit 02d65989335ebff5d9944630239e151253b28f3a, July 8th).

**Comment by Davide-DD** [comment]
The same happens with Linuxbridge

**Comment by Davide-DD** [comment]
I finally discovered why... Now, the ID in /etc/machine-id is formatted as a valid UUID before registering the agent to YAKS, therefore, even if the ID in /etc/machine-id is copied to linux_plugin.json, it's not transformed to a valid UUID before the copy and it will not match the agent UUID. To solve, I made a little modification to fos_install.sh and to Linuxbridge and LXD makefiles, in order to transform machine-id to a valid UUID and then copy it to the destination JSON file: if you think that it can be useful, @gabrik, I can upload the modifications I made.

**Comment by gabrik** [comment]
Thanks @Davide-DD, yes, the update on the UUID was done some commit ago, that was in order to use standard UUID4 format.

Sure, you can contribute your updates opening a Pull Request:
- fork the repo
- apply modification
- send a PR

Thanks!

**Comment by Davide-DD** [comment]
Perfect! I'll keep this opened so I can reference it in the PR.
