### ISSUE TITLE
Is LXD monitoring still in development?

### ISSUE THREAD

**Issue by Davide-DD** [eclipse/fog05#124]
I was trying to get the IP address of an interface of one of my containers, but I kept receiving a monitoring error. I applied a workaround to /etc/fos/plugins/LXD/LXD_plugin to make it work:
1. Moved the code for creating the thread for monitoring to the end of the function run_fdu()
2. Uncommented "c_net = cs.network" line
3. Commented everything below the previous line until the first detailed_state.update(...) statement

Now I can get the IP address from the hypervisor field returned by instance_info method, but I don't understand if it's just a problem of mine or if this feature is still in development.

**Comment by gabrik** [comment]
Hi @Davide-DD, that was supposing to work.
I will check if during one of the PR something went wrong and messed up the code

**Comment by gabrik** [comment]
There was a bug in both LXD plugin and LinuxBridge one.
I'm pushing a new PR that solves this.

Then it is supposed to work in this way
```
a = FIMAPI('10.100.1.242')
>>> a.fdu.instance_info('a7335489-44b8-41db-96c3-bc44944016ed')
{'fdu_uuid': '1b526aa7-408f-4d63-b58c-9e2dfd9451ed', 'node': 'a2d358aa-af2b-42cb-8d23-a89e88b97e5c', 'uuid': 'a7335489-44b8-41db-96c3-bc44944016ed', 'status': 'RUN', 'interfaces': [{'vintf_name': 'eth0', 'status': 'CREATE', 'if_type': 'BRIDGED', 'mac_address': 'be:ef:be:ef:00:02', 'phy_face': 'lxdbr0'}], 'connection_points': [], 'hypervisor_info': {'network': {'eth0': {'hwaddr': 'be:ef:be:ef:00:02', 'addresses': [{'address': '192.168.122.100'}]}}, 'cpu': {'usage': 2148560701}, 'memory': {'usage': 7041024, 'usage_peak': 9412608, 'swap_usage': 0, 'swap_usage_peak': 0}}, 'accelerators': {'fpga': [], 'gpu': []}, 'io_ports': []}
```

So inside `hypervisor_info` you will have all the runtime informations

**Comment by Davide-DD** [comment]
Just tried the fix out... Monitoring still gives me the same problem: in LXD_plugin, it tries to access the network field of the state of the container, but it's empty at the time of access, therefore it returns an error. For what regards my environment, network field gets populated after a successful return of the run method on the FDU instance. What could I possibly be doing wrong?

**Comment by gabrik** [comment]
Ok, this is pretty strange.
So when the container is started you get an error instead of getting the actual state information of the container?
This can be solved by adding a try...except when accessing the LXD APIs, but should not be necessary it is supposed to return an empty string and not raise an error.

Which kind of network configuration are you using?

**Comment by Davide-DD** [comment]
> So when the container is started you get an error instead of getting the actual state information of the container?

Sorry, I meant: when the container is configured, the method __monitor_instance is called and afterwards it fails straight away because the network field is empty (it's going to populate itself at the end of the start method).

> Which kind of network configuration are you using?

I've deployed a network FDU which gives IPs to containers (it has a DHCP). I have two containers, each one has an internal VIRTIO interface with no MAC address statically specified. If you think it could be useful, I can upload logs and FDU descriptors.

**Comment by gabrik** [comment]
> Sorry, I meant: when the container is configured, the method __monitor_instance is called and afterwards it fails straight away because the network field is empty (it's going to populate itself at the end of the start method).

Ok, the method __monitor_instance should not be called when the container is in CONFIGURED state, because as it is not running it is normal to get an error when trying to get the IP address from the LXD API.

I will fix this in the next PR, I was not experiencing the same behaviour because the test script is too fast and right after the configure calls the run so it was not causing error.

**Comment by gabrik** [comment]
PR #132 should solve this.

@Davide-DD can you confirm?

**Comment by Davide-DD** [comment]
Now it doesn't report the error anymore, but when I try to get the information about the addresses after the execution of run_fdu() I find an empty structure as follows:
`{'hypervisor_info': {'network': {'eth0': {'addresses': [{'address': ''}], 'hwaddr': ''}}, 'cpu': {'usage': 815369458}, 'memory': {'swap_usage_peak': 0, 'usage': 27258880, 'usage_peak': 28340224, 'swap_usage': 0}}, 'fdu_uuid': '1e57bb0e-cb41-4b23-bca3-1fa761a83c10', 'uuid': '1ecedd4a-8864-41bc-a593-4b17d71dbda3', 'accelerators': {'fpga': [], 'gpu': []}, 'node': '04729aba-8907-469e-b7a7-558f144df095', 'status': 'RUN', 'interfaces': [{'status': 'CREATE', 'if_type': 'VIRTIO', 'vintf_name': 'eth0', 'cp_id': '0294393a-13ae-411c-8200-4c959ec1c1b5'}], 'io_ports': [], 'connection_points': [{'cp_uuid': 'bbd9595b-75c5-414c-9d9d-8811838be1f7', 'status': 'CREATE', 'uuid': '0294393a-13ae-411c-8200-4c959ec1c1b5'}]}`
I analyzed the LXD plugin stacktrace and I found out that monitoring stops as soon as run_fdu() returns, so maybe it can't get to update the addresses after the containers are properly executed.

**Comment by gabrik** [comment]
Intresting, can you upload the descriptors?

I can try to reproduce your scenario, just using 2 FDUs, one with a DHCP server and the other that will receive the address, and see if I have the same behaviour

**Comment by Davide-DD** [comment]
Here it is my test architecture, I'm deploying together a network and 2 LXC containers. I still haven't tested if using just one FDU alone with the network leads to the same problem.
[Archivio.zip](https://github.com/eclipse/fog05/files/3418526/Archivio.zip)

**Comment by gabrik** [comment]
Thanks I will check and let you know!

**Comment by gabrik** [comment]
Indeed there was a bug in the LinuxBridge plugin, that for some reason is blocking when reading the dnsmasq lease file, #135 use a workaround and make it works.

Can you confirm that after the path it is working?

**Comment by Davide-DD** [comment]
Everything is working fine now, thanks @gabrik!
