### ISSUE TITLE
[BUG]Got error while executing "make install" under "fog05/fos-plugins/linuxbridge/"

### ISSUE THREAD

**Issue by wuwei3** [eclipse/fog05#133]
**Describe the bug**
  While execting the "make install" under "fog05/fos-plugins/linuxbridge/" folder, got the error, see the log file

   
[error.txt](https://github.com/eclipse/fog05/files/3416895/error.txt)

 I install the fog05 in ubuntu 16,04, this step was ok in ubuntu14. I don't know why it cannot work in ubuntu16.

**To Reproduce**
1. Go to 'fog05/fos-plugins/linuxbridge/'
2.  execute the "make install" command
3. See error

**Desktop (please complete the following information):**
 - OS: ubuntu 16
 - Version: git clone from master
 - Involved plugin: All

**Comment by gabrik** [comment]
Hi @wuwei3 

From your log I see that 

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=563 -DPSUTIL_LINUX=1 -I/usr/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    psutil/_psutil_common.c:9:20: fatal error: Python.h: No such file or directory
    compilation terminated.
```

You are missing `Pyhton.h` with should be part of a python installation, can you check if python3-dev is installed? If not install it then the error should disappear

**Comment by wuwei3** [comment]
I solved this issue, you could close it. many thanks.
