### ISSUE TITLE
Fog05 hags when you deploy lxc with wi-fi interface

### ISSUE THREAD

**Issue by milangroshev** [eclipse/fog05#138]
I want to deploy lxc container with wi fi interface using fog05 python API, but the container will not start. On the destination machine i can see the container in STOP state and on the host machine where i run the script it blocks on instantiate(). I am ruining the latest version of fog05 available on git with the LXD_plugin.

Descriptor:
{
    "uuid": "1e57bb0e-cb41-4b23-bca3-1fa761a83c02",
    "name": "test_1",
    "computation_requirements": {
        "cpu_arch": "x86_64",
        "cpu_min_freq": 0,
        "cpu_min_count": 1,
        "ram_size_mb": 128.0,
        "storage_size_gb": 5.0
    },
    "image": {
        "uri": "lxd://alpine/3.6",
        "checksum": "",
        "format": ""
    },
    "hypervisor": "LXD",
    "migration_kind": "COLD",
    "interfaces": [
        {
            "name": "wlan0",
            "is_mgmt": false,
            "if_type": "EXTERNAL",
            "mac_address": "be:ef:be:ef:00:01",
            "virtual_interface": {
                "intf_type": "PHYSICAL",
                "vpci": "0:0:0",
                "bandwidth": 10
            },
            "cp_id": ""
        }
    ],
    "io_ports": [],
    "connection_points": [
        {
            "uuid": "a47a8819-72e5-4b4e-86fd-fc30c9fda68b",
            "pair_id": ""
        }
    ],
    "depends_on": []
}

Use the python3 API and launch the container using the provided descriptor.
In normal case i should see the container up and running after the script has finished.

- OS: Ubuntu
- Version 16.04
- Involved plugin LXD
- LXD version: 3.15
- pylxd: 2.2.10

**Comment by gabrik** [comment]
Thanks @milangroshev
This is actually related to LXD, using an "old" version of LXD, like 3.0 solves the problem, this is related to https://github.com/lxc/lxc/issues/3105
