### ISSUE TITLE
[BUG] pylxd.exceptions.ClientConnectionFailed

### ISSUE THREAD

**Issue by wayne43290** [eclipse/fog05#91]
**Describe the bug**
While starting the fog system, the LXD_plugin reports error: pylxd.exceptions.ClientConnectionFailed

This problem is the same as the issue here: https://github.com/lxc/pylxd/issues/317
And I did some workaround based on this comment: https://github.com/lxc/pylxd/issues/317#issuecomment-403276328
I inserted some code into _/etc/fos/plugins/LXD/LXD_plugin_, around line 81 in the _def start_runtime(self)_: 
`Client()` => `Client(endpoint='https://127.0.0.1:8443', verify=False)`

Is there a formal way to deal with this error?

 - Hardware: Nvidia TX2
 - OS: Ubuntu 16.04.6 LTS
 - Version 4.4.38-tegra aarch64
 - Involved plugin LXD

**Screenshot**
![11](https://user-images.githubusercontent.com/4182598/58376931-66f3d580-7fa8-11e9-8d02-dd4b77fa85a0.png)

**Comment by gabrik** [comment]
Thanks @wayne43290 
I think your workaround is fine, there is no formal way for this issue.
This will be solved in the next PR.

**Comment by gabrik** [comment]
This can be related to: https://github.com/lxc/pylxd/issues/365

**Comment by gabrik** [comment]
Solved by https://github.com/eclipse/fog05/pull/97
